import requests

# Replace this variable with the S3 URL generated by s3.generate_presigned_url
s3_url = "bkt-test2023-103131623091.s3.amazonaws.com/2dd730c9-cd17-49c3-b9b4-0a4dd2a5691f.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIARQAY7V2ZUYRNANFF%2F20230923%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Date=20230923T031408Z&X-Amz-Expires=6000&X-Amz-SignedHeaders=host&X-Amz-Security-Token=IQoJb3JpZ2luX2VjECsaDmFwLXNvdXRoZWFzdC0xIkgwRgIhAMuB5PBOnVlCg74rBBiDYG8qjXGMjYllXlc%2FHCyuyfG6AiEAvnCb%2B%2FoK5PThiCdGfNJ7OHQIPHnnWw3fXoCs3nUVSecq7QIIJBAAGgwxMDMxMzE2MjMwOTEiDIj7dqE5%2FnQnXcuLsirKAuzya0RHdQsjdlCx4Wqsqv4xfM3e0eTLi4Vsfe32%2F%2FxOq9szXU5VXqawmzieizMKcurP3n1DW3%2F3Pu39M4xmfI4OvDG%2F0Q4OnIzTgRKGI0eHraqIFLGlMej%2BCcwQdvvdz2XZuVKSMV7nkec4DnlKZbgPGs2%2FcmrHTEuOxngDqhBqteeaG4mjnEhDiJdg%2BUSN3vuYvKV%2F2eL7jqiX9oVwjiUiu%2F0KNXa19saJtYIwtxfB9L0s9v6IetDoT5HeMR2KLctYDutqnnlCoKvRdKLleIn%2FcHFREFDFdNUt%2BEYaV9lts7vbFfjwNADDwmdG5v7Qv7ccNnZtMhDNIja9gmiKuKFAlX%2BhYg7NFae8ZCweqas52fYa1StPoTTydXI%2FuM2IzRo4Qen1DVnvSh7pwPOAQhpZwoYorH0DU%2FFv5W1YP4MI4t1Ow8A4Tx7r5DD%2Br7moBjqdAVsh2GLWi%2Ba7BCXsQEwz4SLtCd3bctDxeDh8FglM39ytru1CSzXXnPEommmS%2FNrUp4yAMRXl2N8bey3WzZiBvsgtAy%2B2hIt0OCshcmcCCOP8Mr%2BjIGzIk6xjNUS%2BvvvVDqVrqtnaDlpNtvClnzOB2e9ZnZRSV10Nvd2vFa8M01c1B%2FxEkxCWZUNMR4p72G73ehvmi9LvbF2pOb%2FcdQQ%3D&X-Amz-Signature=6f06b9ab359aa39460850b37e2b94dcb283fbdaecc429ca30150fed124097b17"
senUrl = "https://"+s3_url
file_path = "test.png"

try:
    with open(file_path, "rb") as file:
        response = requests.put(senUrl, data=file)

    if response.status_code == 200:
        print("PUT request was successful")
    else:
        print(f"PUT request failed with status code {response.status_code}")

except Exception as e:
    print(f"An error occurred: {str(e)}")
