import requests

# Replace this variable with the S3 URL generated by s3.generate_presigned_url
s3_url = ""
senUrl = "https://"+s3_url
file_path = "test.png"

try:
    with open(file_path, "rb") as file:
        response = requests.put(senUrl, data=file)

    if response.status_code == 200:
        print("PUT request was successful")
    else:
        print(f"PUT request failed with status code {response.status_code}")

except Exception as e:
    print(f"An error occurred: {str(e)}")
