import requests

# Replace this variable with the S3 URL generated by s3.generate_presigned_url
s3_url = "bkt-p2-103131623091.s3.amazonaws.com/4cff8755-ca6e-444e-808d-c1928ed375ac.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIARQAY7V2Z3R354R5K%2F20230923%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Date=20230923T075627Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEDAaDmFwLXNvdXRoZWFzdC0xIkcwRQIgUyWAc5eqncGSsSAEkEfEMb5M5iCcXGps3Xm1DVD0PfECIQDp%2FX9YdtLB2ASZSFQ1fGS9XP1APUtXw9V99Bfy4RCMTyrtAggpEAAaDDEwMzEzMTYyMzA5MSIMrc4rss9R8Ugc%2FZ2%2BKsoCRNCLodsF6kLZPsjPDqlhUaSS1qtuqs6bzvdASjUauBsPkhP7Ddnp561Dzq6vAtiRwu0tEGsJEF1UbEdWUnxm0zDjheky%2Fe4ZkOa7hXmvBs84GvcgDoRhI3PaUTh%2BtqK%2FYf%2BqLQ4PBVCjGA2wnqKJCpkUXIX0K6c05kKFQehCSCzL8mfuM8iG8J41Aic%2Fu5qJRsP70FAkHU22UxASGHrDlMffPHtc0cQFI%2Fxu%2B1jvpUSET2rfpxvlMpl4gAJGbSsvFCodZuA%2Bew6DMXt6x2USZrQhxoRym4RB5SpxFNULtd%2Bc9TuMclkCu7cpMbUguxdDU7RqUPIsuHIkHZEdeC76EvryBpERwTb43HLmTmZfTgXcLjqUelrWPjtWj3CVypegTZgJa%2FMQaeFHWZGJxE48kwN77frv35o0Cymqc6w9bhek4mxOOFS5NEkyMIazuqgGOp4BLkCGvlAQIKFNVgl7XyYy1tJK8685EkKaPWKQi7%2F%2FDjO9MOdlW7cvF0aktIwbjnFf2K12rl2xQ7BGlFid65MTZOy%2FsJ10tf776G1vcuXQP72Y%2BfzG4i3clS1%2Bs0WTuC7reRZivJXCDYPQeUUT2lejH3qCLLKGLalVG79dlsemIcowK60cLeQQkRbR6HXTbd5eS%2FpAgGorgT%2F5f0bRYzI%3D&X-Amz-Signature=707bbfc3b45d4070340eef64956a904206da254ef304a091d141b6bbf8874437"
sendUrl = "https://"+s3_url
file_path = "test.png"

try:
    with open(file_path, "rb") as file:
        response = requests.put(s3_url, data=file)

    if response.status_code == 200:
        print("PUT request was successful")
    else:
        print(f"PUT request failed with status code {response.status_code}")

except Exception as e:
    print(f"An error occurred: {str(e)}")
